version: '3'

services:

  djdocker:
    build: .
    volumes:
      - .:/opt/services/djdocker/src
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djdocker
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
